// <auto-generated />
namespace WebApplication53.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Many2Many2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Many2Many2));
        
        string IMigrationMetadata.Id
        {
            get { return "202008151241258_Many2Many2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
